drop database if exists runningsongs;
drop table if exists entries;
drop table if exists song;
drop table if exists band;
create table song (id serial primary key, name varchar(254) not null, details text not null);
create table band (id serial primary key, name varchar(254) unique not null, details text not null);
create table entries (band int not null, song int not null, primary key (band, song),
      foreign key(song) references song(id), foreign key(band) references band(id));
insert into song (name, details) values ('Superheros', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Fusce vitae erat eu enim facilisis egestas in nec tellus. Phasellus rhoncus ante neque, et pulvinar turpis accumsan id. Morbi dignissim id tortor eu maximus. Mauris aliquet pellentesque rhoncus. Suspendisse potenti. In leo odio, aliquet quis libero ut, eleifend sagittis est. Nulla accumsan nulla id ornare laoreet. Morbi iaculis justo quam, vel ultrices massa semper quis. Aenean viverra volutpat dui id dictum. Proin euismod lacinia euismod. Ut egestas felis id tortor consequat, quis sagittis nunc sagittis. Aenean convallis ut diam ac euismod. Mauris elementum pulvinar consequat. Donec ac nibh posuere, semper arcu sit amet, aliquam risus. Aliquam sit amet massa libero.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into song (name, details) values ('Hall of Fame', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into song (name, details) values ('In the End', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into song (name, details) values ('Numb', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into song (name, details) values ('Here''s to Us', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into song (name, details) values ('Freak Like Me', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into song (name, details) values ('Livin'' On A Prayer', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into song (name, details) values ('ME!', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into song (name, details) values ('The One That Got Away', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into song (name, details) values ('I''m Still Standing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into song (name, details) values ('Let''s See How Far We''ve Come', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into song (name, details) values ('What''s My Age Again?', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into song (name, details) values ('Who Knew?', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into band (name, details) values ('The Script', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into band (name, details) values ('Linkin Park', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into band (name, details) values ('Halestorm', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into band (name, details) values ('Blink 182', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into band (name, details) values ('Bon Jovi', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into band (name, details) values ('Katy Perry', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into band (name, details) values ('Taylor Swift', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into band (name, details) values ('Matchbox 20', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into band (name, details) values ('Elton John', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into band (name, details) values ('Pink', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus est, facilisis ac est id, elementum condimentum nulla. Sed et gravida dolor. Fusce tempor egestas velit quis facilisis. Nunc a varius quam. Vivamus aliquam, ligula quis venenatis pharetra, libero sapien posuere felis, quis rutrum enim est non nisl. Vestibulum semper congue felis, sed accumsan neque malesuada non. Morbi non ultrices leo. Curabitur interdum dolor id quam auctor imperdiet. Mauris augue mi, viverra nec maximus porttitor, euismod in augue. Phasellus bibendum auctor maximus. Aliquam erat volutpat. Phasellus sodales orci non pharetra vestibulum. Donec euismod neque vel elementum ultrices. Nunc luctus mi nec mauris volutpat, non dignissim diam auctor. Aliquam vitae fringilla metus.

Integer tempus suscipit sapien sed faucibus. Praesent dignissim imperdiet sagittis. Morbi a mollis urna. Praesent vestibulum orci at sapien ultricies ultricies. Vivamus nec justo in quam accumsan accumsan. Praesent congue augue in nulla pretium, nec rutrum metus tincidunt. Curabitur rutrum pulvinar enim in tristique. Nunc placerat, ipsum eu tempor gravida, libero ante vulputate lectus, ac congue mauris nibh eget enim.

Nullam sed neque ipsum. Aliquam erat volutpat. Aenean volutpat nisl ut odio varius auctor. Sed quis augue nec eros interdum lacinia. Praesent laoreet eros nec turpis sollicitudin venenatis nec at erat. Etiam eget diam enim. Vivamus dapibus venenatis mauris vel consequat.

Fusce eget mollis tortor. Nulla facilisi. Ut imperdiet neque quis porta molestie. Sed non aliquet velit, vel lacinia leo. Nunc sapien ante, gravida nec scelerisque et, mattis a metus. Morbi pharetra neque vel molestie tempus. Vivamus vestibulum eu dui sit amet mattis. Nam tincidunt finibus blandit. In id varius ex. Phasellus et dictum erat. Vestibulum maximus, purus quis pharetra gravida, lacus sem volutpat felis, vel cursus sem elit sit amet ante.');

insert into entries (band, song) values (1,1);
insert into entries (band, song) values (1,2);
insert into entries (band, song) values (2,3);
insert into entries (band, song) values (2,4);
insert into entries (band, song) values (3,5);
insert into entries (band, song) values (3,6);
insert into entries (band, song) values (4,12);
insert into entries (band, song) values (5,7);
insert into entries (band, song) values (6,9);
insert into entries (band, song) values (7,8);
insert into entries (band, song) values (8,11);
insert into entries (band, song) values (9,10);
insert into entries (band, song) values (10,13);